services:
  web:
    build:
      context: ./web
    ports:
      - "5001:5001"
    volumes:
      - ./web:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DB=project
    depends_on:
      - db
volumes:
  mysql_data:
