services:
  web:
    build:
      context: ./web
    ports:
      - "80:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./web:/app
    networks:
      - webnet

networks:
  webnet: