"""empty message

Revision ID: 57ff05724673
Revises: fcfb3ba7bfba
Create Date: 2024-08-22 20:32:35.271645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ff05724673'
down_revision = 'fcfb3ba7bfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needed_grades_comment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('needed_grades_comment')

    # ### end Alembic commands ###
