"""empty message

Revision ID: c0acc5eef51e
Revises: 57ff05724673
Create Date: 2024-08-22 21:13:58.998690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0acc5eef51e'
down_revision = '57ff05724673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('grades', sa.Text(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_description', sa.String(length=255), nullable=True),
    sa.Column('unique_token', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_token')
    )
    op.drop_table('subject')
    op.drop_table('student_history')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('average_score', sa.FLOAT(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('title_description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('unique_token', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_token')
    )
    op.create_table('student_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.VARCHAR(length=50), nullable=False),
    sa.Column('average_score', sa.FLOAT(), nullable=False),
    sa.Column('improved', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('marks', sa.VARCHAR(length=100), nullable=True),
    sa.Column('average', sa.FLOAT(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('needed_grades_comment', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student_record')
    # ### end Alembic commands ###
