"""empty message

Revision ID: db394b2ecb04
Revises: ef3df43f53c9
Create Date: 2024-08-23 17:17:23.747839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db394b2ecb04'
down_revision = 'ef3df43f53c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.String(length=50), nullable=False))
        batch_op.alter_column('student_name',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('title_description',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('needed_grades',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('unique_token',
               existing_type=sa.TEXT(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.alter_column('unique_token',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(length=36),
               existing_nullable=False)
        batch_op.alter_column('needed_grades',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=False)
        batch_op.alter_column('title_description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.drop_column('period')

    # ### end Alembic commands ###
