"""Add needed_grades to StudentRecord

Revision ID: ef3df43f53c9
Revises: c0acc5eef51e
Create Date: 2024-08-22 21:42:43.477582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3df43f53c9'
down_revision = 'c0acc5eef51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needed_grades', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.drop_column('needed_grades')

    # ### end Alembic commands ###
