"""Initial migration

Revision ID: fe12e146336c
Revises: 
Create Date: 2024-08-22 18:18:44.108301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe12e146336c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=10), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_description', sa.Text(), nullable=True),
    sa.Column('unique_token', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_token')
    )
    op.create_table('student_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('improved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_history')
    op.drop_table('student')
    # ### end Alembic commands ###
